# Site
repository: jamini68
favicon: images/favicon.ico

# Personal info
name: Javad Amini
title: Senior Network System Administrator
email: masteryahoo@gmail.com
website: www.github.com/jamini68

# Social links
github_username:  jamini68
instagram_username: gorj_amen

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 In my childhood I was intersted in <mark>Computer</mark> and new <mark>Technologies</mark>. When I grew up I tried to have goal so I learned language programming such as java, C++, C#, VB, HTML 5, Css and etc and I did some projects too.

 After graduation I just knew that I want work with computer so at the begining I was hired by <mark>Datak Company</mark> for 9 months, I undrestand Networking is very good for me so after 9 months in Mojnews Agency I learned Microsoft MSCE 2003 and A+. After that I learned Cisco and LPIC 1.
 
 
 Some of my Qualification as below:
 
 1) Mastery of <mark>Microsoft Office</mark>.
 
 2) Familiarity with virtualization programs such as <mark>VMware Workstation</mark> and installation of different operating systems and creating an internal network between operating systems.
 
 3) Familiarity with <mark>ESXi 6</mark> and its installation.
 
 4) Installation of <mark>Plesk</mark> application
 
 5) Flashing Android phones and installing all kinds of custom ROMs and software troubleshooting.
 
 6) Website design with <mark>Joomla</mark> and <mark>wordpress</mark>.
 
 7) English language proficiency and 3 months English language strengthening course in <mark>Cambridge</mark>.
 
 8) Fluency in <mark>French</mark>.



# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
